# Site settings
title: Summer Project
email: charfran@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  This project represents aspects of my summer spent interning in 
  New York City and serves as a place of reference for my personal 
  experiences and memories, which I will never forget. 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
twitter_username: charliefran_
github_username:  charliefran
strict_front_matter: true
sass:
  sass_dir: css
  style: expanded
collections:
  posters:
    output: true
    permalink: /:collection/:slug/
    defaults:
      -
        scope:
          path: "assets/posters"
          type: "posters"
        values:
          image: true
          layout: poster
          paginate: 4
include: ["_pages","_posters","_about","_index"]





# Build settings
markdown: kramdown
permalink: /:title/
